/**
 * Project Files & Sharing (Tier-2) · S12 — parallel approval routing for shop
 * drawings (milestone #12, issue #226). Pure, dependency-free routing logic so
 * the "approved only after every required reviewer signs off" rule is unit-tested
 * in isolation from Supabase and React.
 *
 * The model: a document is routed to N reviewers IN PARALLEL (architect + GC +
 * PM by default). Each reviewer leaves one status. The document only moves to
 * Approved once ALL required reviewers approve; a single "needs revision" routes
 * it back regardless of the others. Three statuses, three colours.
 */

/** The reviewer roles a shop drawing is routed to in parallel. */
export const REVIEWER_ROLES = ["architect", "gc", "pm"] as const;
export type ReviewerRole = (typeof REVIEWER_ROLES)[number];

/** Display labels for each reviewer role (used in the owner routing panel). */
export const REVIEWER_ROLE_LABELS: Record<ReviewerRole, string> = {
  architect: "Architect",
  gc: "General Contractor",
  pm: "Project Manager",
};

/** The three review states. `pending` = routed, awaiting this reviewer. */
export const APPROVAL_STATUSES = ["pending", "approved", "needs_revision"] as const;
export type ApprovalStatus = (typeof APPROVAL_STATUSES)[number];

/** One reviewer's slot in a document's routing. */
export type DocumentApproval = {
  id: string;
  documentId: string;
  reviewerRole: ReviewerRole;
  status: ApprovalStatus;
  reviewerName: string | null;
  notes: string | null;
  /** Set when the reviewer leaves a non-pending status; null while pending. */
  reviewedAt: string | null;
  createdAt: string;
};

/**
 * The document-level routing outcome — the SAME three states as an individual
 * review, computed across all required reviewers:
 *   needs_revision  → at least one reviewer rejected (rejection wins)
 *   approved        → every required reviewer approved
 *   pending         → still waiting on someone, nobody rejected
 */
export type RoutingStatus = ApprovalStatus;

/**
 * Build the initial pending routing — one row per required reviewer role. IDs
 * are generated by the caller's store; here each row is a plain pending slot.
 */
export function makePendingApprovals(
  documentId: string,
  roles: readonly ReviewerRole[] = REVIEWER_ROLES
): DocumentApproval[] {
  const now = new Date().toISOString();
  return roles.map((role) => ({
    id: "",
    documentId,
    reviewerRole: role,
    status: "pending" as ApprovalStatus,
    reviewerName: null,
    notes: null,
    reviewedAt: null,
    createdAt: now,
  }));
}

/** Latest status per role (last write wins if duplicates ever slip in). */
function statusByRole(approvals: readonly DocumentApproval[]): Map<ReviewerRole, ApprovalStatus> {
  const map = new Map<ReviewerRole, ApprovalStatus>();
  for (const a of approvals) map.set(a.reviewerRole, a.status);
  return map;
}

/**
 * The parallel gate: true ONLY when every required role has a row AND every one
 * of them is `approved`. A missing role, a pending one, or any rejection → false.
 */
export function allApproved(
  approvals: readonly DocumentApproval[],
  requiredRoles: readonly ReviewerRole[] = REVIEWER_ROLES
): boolean {
  const byRole = statusByRole(approvals);
  return requiredRoles.every((role) => byRole.get(role) === "approved");
}

/**
 * The document-level outcome. Rejection takes precedence (route it back now),
 * then full approval, otherwise still pending.
 */
export function computeRoutingStatus(
  approvals: readonly DocumentApproval[],
  requiredRoles: readonly ReviewerRole[] = REVIEWER_ROLES
): RoutingStatus {
  const byRole = statusByRole(approvals);
  if (requiredRoles.some((role) => byRole.get(role) === "needs_revision")) {
    return "needs_revision";
  }
  if (allApproved(approvals, requiredRoles)) return "approved";
  return "pending";
}

/** Count of required reviewers who have approved (for the "2 of 3" progress hint). */
export function approvedCount(
  approvals: readonly DocumentApproval[],
  requiredRoles: readonly ReviewerRole[] = REVIEWER_ROLES
): number {
  const byRole = statusByRole(approvals);
  return requiredRoles.filter((role) => byRole.get(role) === "approved").length;
}

/**
 * The 3-status colour system. Pending = amber (at-risk), Approved = green
 * (on-track), Needs Revision = red (blocked) — reusing the project's status
 * design tokens (docs/DESIGN.md) so the routing reads consistently with the rest
 * of the dashboard. `pillClass` styles the status pill; `dotClass` the leading dot.
 */
export const APPROVAL_STATUS_META: Record<
  ApprovalStatus,
  { label: string; pillClass: string; dotClass: string }
> = {
  pending: {
    label: "Pending Review",
    pillClass: "bg-status-at-risk-soft/40 text-status-at-risk",
    dotClass: "bg-status-at-risk",
  },
  approved: {
    label: "Approved",
    pillClass: "bg-status-on-track-soft/40 text-status-on-track",
    dotClass: "bg-status-on-track",
  },
  needs_revision: {
    label: "Needs Revision",
    pillClass: "bg-status-blocked-soft/40 text-status-blocked",
    dotClass: "bg-status-blocked",
  },
};
