import type { Job } from "@shared/lib/types";

export const SEED_JOBS: Job[] = [
  {
    id: "1",
    code: "GW-2026-001",
    name: "SayWell — Phase 2 Suite Kitchens",
    client: "SayWell Developments",
    address: "1042 Yates St, Victoria BC",
    template: "full_project",
    pipelineStatus: "in_production",
    healthStatus: "on_track",
    currentMilestone: "cnc",
    installDate: "2026-06-22",
    revenue: 84200,
    costs: [
      { id: "c1", category: "materials", label: "Sheet goods + edgebanding", amount: 18400 },
      { id: "c2", category: "materials", label: "Hardware (Blum, pulls)", amount: 6200 },
      { id: "c3", category: "materials", label: "Solid surface counters", amount: 9800 },
      { id: "c4", category: "labour", label: "Shop fabrication", amount: 14600 },
      { id: "c5", category: "labour", label: "Site install (3 days)", amount: 4800 },
      { id: "c6", category: "overhead", label: "Delivery + crane", amount: 1500 },
    ],
    notes: "Phase 2 of 4. Milestone payment due on cabinet box delivery.",
    invoice: {
      number: "INV-2026-001",
      issuedDate: "2026-05-04",
      dueDate: "2026-05-18",
      lineItems: [
        { description: "Custom kitchen cabinetry — Suite 301", qty: 1, unitPrice: 21050 },
        { description: "Custom kitchen cabinetry — Suite 302", qty: 1, unitPrice: 21050 },
        { description: "Custom kitchen cabinetry — Suite 303", qty: 1, unitPrice: 21050 },
        { description: "Custom kitchen cabinetry — Suite 304", qty: 1, unitPrice: 21050 },
      ],
    },
  },
  {
    id: "2",
    code: "GW-2026-002",
    name: "Raubyn — Oak Bay Heritage Reno",
    client: "Raubyn Design Studio",
    address: "2240 Beach Dr, Oak Bay BC",
    template: "full_project",
    pipelineStatus: "in_design",
    healthStatus: "on_track",
    currentMilestone: "design",
    installDate: "2026-07-14",
    revenue: 62500,
    costs: [
      { id: "c1", category: "materials", label: "Rift white oak", amount: 14200 },
      { id: "c2", category: "materials", label: "Hardware + finish", amount: 4100 },
      { id: "c3", category: "labour", label: "Shop fabrication", amount: 16800 },
      { id: "c4", category: "labour", label: "Install + scribe", amount: 5600 },
      { id: "c5", category: "overhead", label: "Drafting + design liaison", amount: 1800 },
    ],
    notes: "Anchor relationship — premium finish, full Raubyn drawing set.",
    invoice: {
      number: "INV-2026-002",
      issuedDate: "2026-05-04",
      dueDate: "2026-05-18",
      lineItems: [
        { description: "Kitchen — rift white oak base + uppers", qty: 1, unitPrice: 38500 },
        { description: "Pantry millwork wall", qty: 1, unitPrice: 14200 },
        { description: "Mudroom built-ins", qty: 1, unitPrice: 9800 },
      ],
    },
  },
  {
    id: "3",
    code: "GW-2026-003",
    name: "Smith Residence — Refacing",
    client: "Linda Smith",
    address: "3815 Cedar Hill Rd, Saanich BC",
    template: "refacing",
    pipelineStatus: "in_finishing",
    healthStatus: "at_risk",
    currentMilestone: "finishing",
    installDate: "2026-05-20",
    revenue: 14800,
    costs: [
      { id: "c1", category: "materials", label: "Slab door blanks (28 doors)", amount: 4200 },
      { id: "c2", category: "materials", label: "Hinges + soft-close", amount: 720 },
      { id: "c3", category: "labour", label: "Spray finishing (2K poly)", amount: 5400 },
      { id: "c4", category: "labour", label: "Install + adjust", amount: 1900 },
    ],
    notes: "Spray booth scheduling tight — flag if other jobs push.",
    invoice: {
      number: "INV-2026-003",
      issuedDate: "2026-05-04",
      dueDate: "2026-05-18",
      lineItems: [
        { description: "Refacing — 28 doors + 4 drawer fronts", qty: 1, unitPrice: 12200 },
        { description: "New soft-close hinges", qty: 56, unitPrice: 18 },
        { description: "Install + adjustment", qty: 1, unitPrice: 1592 },
      ],
    },
  },
  {
    id: "4",
    code: "GW-2026-004",
    name: "Toolpath — Shop Office Built-ins",
    client: "Toolpath Workshop",
    address: "104 Crease Ave, Victoria BC",
    template: "full_project",
    pipelineStatus: "installing",
    healthStatus: "on_track",
    currentMilestone: "install",
    installDate: "2026-05-12",
    revenue: 21400,
    costs: [
      { id: "c1", category: "materials", label: "Baltic birch ply + maple", amount: 4800 },
      { id: "c2", category: "materials", label: "Hardware + LED tape", amount: 1100 },
      { id: "c3", category: "labour", label: "Shop fabrication", amount: 6200 },
      { id: "c4", category: "labour", label: "Install (2 days)", amount: 2400 },
      { id: "c5", category: "overhead", label: "Delivery", amount: 320 },
    ],
    notes: "Trade — repeat referral source, deliver on the high end of spec.",
    invoice: {
      number: "INV-2026-004",
      issuedDate: "2026-05-04",
      dueDate: "2026-05-18",
      lineItems: [
        { description: "Office desk + credenza built-in", qty: 1, unitPrice: 14600 },
        { description: "Reception millwork wall", qty: 1, unitPrice: 6800 },
      ],
    },
  },
  {
    id: "5",
    code: "GW-2026-005",
    name: "Patel — Spray Finishing Only",
    client: "Anika Patel",
    address: "771 Lampson St, Esquimalt BC",
    template: "spray_finishing",
    pipelineStatus: "sold",
    healthStatus: "blocked",
    currentMilestone: "cnc",
    installDate: "2026-06-01",
    revenue: 6200,
    costs: [
      { id: "c1", category: "materials", label: "2K poly + primer", amount: 980 },
      { id: "c2", category: "labour", label: "Spray + cure (4 days)", amount: 3200 },
      { id: "c3", category: "labour", label: "Sand + prep", amount: 1400 },
      { id: "c4", category: "overhead", label: "Drop-off / pickup logistics", amount: 240 },
    ],
    notes: "BLOCKED: client hasn't dropped off doors. Follow up Tue.",
    invoice: {
      number: "INV-2026-005",
      issuedDate: "2026-05-04",
      dueDate: "2026-05-18",
      lineItems: [
        { description: "Spray finishing — 22 raw doors (both sides)", qty: 22, unitPrice: 240 },
        { description: "Drop-off / return delivery", qty: 1, unitPrice: 920 },
      ],
    },
  },
  {
    id: "6",
    code: "GW-2026-006",
    name: "Kitchencraft — Install Only",
    client: "Kitchencraft Trade",
    address: "118 Burnside Rd, Victoria BC",
    template: "install_only",
    pipelineStatus: "complete",
    healthStatus: "complete",
    currentMilestone: "install",
    installDate: "2026-04-28",
    revenue: 9800,
    costs: [
      { id: "c1", category: "labour", label: "Install crew (3 days × 2)", amount: 5400 },
      { id: "c2", category: "materials", label: "Shims, fasteners, scribe stock", amount: 280 },
      { id: "c3", category: "overhead", label: "Truck + fuel", amount: 220 },
    ],
    notes: "Closed clean. GM benchmark for install-only template.",
    invoice: {
      number: "INV-2026-006",
      issuedDate: "2026-04-29",
      dueDate: "2026-05-13",
      lineItems: [
        { description: "Install labour — 18 cabinet boxes", qty: 1, unitPrice: 8400 },
        { description: "Materials + truck", qty: 1, unitPrice: 1400 },
      ],
    },
  },
];

export function getJob(id: string): Job | undefined {
  return SEED_JOBS.find((j) => j.id === id);
}
